[package]
name = "zenroom"
version = "0.2.0"
authors = ["Danilo Spinella <oss@danyspin97.org>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
thiserror = "1.0"

[build-dependencies]
bindgen = "0.53.1"

[dev-dependencies]
serde_json = "1.0"
